DROP TABLE IF EXISTS FILM_GENRE;
DROP TABLE IF EXISTS LIKES;
DROP TABLE IF EXISTS FRIENDSHIP;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS FILM;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS MPA;

CREATE TABLE MPA (
    id INTEGER PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE FILM (
    id INTEGER PRIMARY KEY,
    name VARCHAR,
    description VARCHAR,
    release_date DATE,
    duration INTEGER,
    mpa_id INTEGER,
    FOREIGN KEY (mpa_id) REFERENCES MPA(id)
);

CREATE TABLE GENRE (
    id INTEGER PRIMARY KEY,
    desc VARCHAR
);

CREATE TABLE USERS (
    id INTEGER PRIMARY KEY,
    birthday DATE,
    email VARCHAR NOT NULL,
    login VARCHAR NOT NULL
);

CREATE TABLE LIKES (
    id INTEGER PRIMARY KEY,
    film_id INTEGER,
    user_id INTEGER,
    FOREIGN KEY (film_id) REFERENCES FILM(id),
    FOREIGN KEY (user_id) REFERENCES USERS(id)
);

CREATE TABLE FILM_GENRE (
    id INTEGER PRIMARY KEY,
    film_id INTEGER,
    genre_id INTEGER,
    FOREIGN KEY (film_id) REFERENCES FILM(id),
    FOREIGN KEY (genre_id) REFERENCES GENRE(id)
);

CREATE TABLE friendship (
    id INTEGER PRIMARY KEY,
    user_id INTEGER,
    friend_id INTEGER,
    accepted BOOLEAN,
    FOREIGN KEY (user_id) REFERENCES USERS(id),
    FOREIGN KEY (friend_id) REFERENCES USERS(id)
);

ALTER TABLE film
ADD CONSTRAINT fk_film_mpa
FOREIGN KEY (mpa_id) REFERENCES MPA(id);